import os
import logging

from lastmiledelivery.conf.environment import get_config

log_format = ' '.join([
    '[%(asctime)s]',
    '[%(process)d-%(thread)d]',
    '%(levelname)s',
    '-',
    '%(message)s'
])

formatter = logging.Formatter(log_format)


def setup_config_logger(app):

    # TODO: Generated by python uuid.uuid4. Get a better key later on
    # app.secret_key = "2421da99-1770-4949-90a0-71c09d409fbb"
    # agro_env = os.environ.get('AGRO_ENV','dev')
    # config = get_config(agro_env)
    # app.config.from_object(config)
    app.debug_log_format = log_format

    if not app.debug:
        logHandler = logging.StreamHandler()
        logHandler.setFormatter(formatter)
        logHandler.setLevel(logging.DEBUG)
        app.logger.addHandler(logHandler)
        app.logger.setLevel(logging.DEBUG)

    # app.logger.info("Loaded environment: " + agro_env)